# ===================================================================
# Copyright © 2025 Sackey Ezekiel Etrue
# Distributed under the terms of the MIT license.
# ===================================================================

load("@rules_cc//cc:cc_library.bzl", "cc_library")
#===========================
# Build C++ Library        #
#===========================

cc_library(
	name = "myjson",
	srcs = [
		"src/myjson.cpp",
	],
	hdrs = glob(["include/myjson/*.h", "include/myjson/*.hpp"]),
    linkstatic = True,
	visibility = ["//visibility:public"],
	includes = ["include"],
	copts = ["-std=c++17"],
)

#===========================
# Build C Library          #
#===========================

cc_library(
	name = "myjsonc",
	srcs = [
		"src/myjsonc.cpp",
	],
	hdrs = glob(["include/myjson/*.h", "include/myjson/*.hpp"]),
    linkstatic = True,
	visibility = ["//visibility:public"],
	includes = ["include"],
	copts = ["-std=c++17"],
	deps = [":myjson"],
)

# ===================================================================
